const sellNowInterface: string[] = [
  'function DOMAIN_SEPARATOR() view returns (bytes32)',
  'function calculateDigest(uint256 nonce, ((bytes32 loanId, uint256 aggLoanPrice, uint256 aggLtv, uint256 aggLiquidationThreshold, uint88 totalAssets, uint256 nonce, uint256 deadline) loan, bytes32 assetId, address marketAdapter, address marketApproval, uint256 marketPrice, address underlyingAsset, address from, address to, bytes data, uint256 value, uint256 nonce, uint256 deadline) signSellNow) view returns (bytes32 digest)',
  'function forceSell((address collection, uint256 tokenId) asset, ((bytes32 loanId, uint256 aggLoanPrice, uint256 aggLtv, uint256 aggLiquidationThreshold, uint88 totalAssets, uint256 nonce, uint256 deadline) loan, bytes32 assetId, address marketAdapter, address marketApproval, uint256 marketPrice, address underlyingAsset, address from, address to, bytes data, uint256 value, uint256 nonce, uint256 deadline) signSellNow, (uint8 v, bytes32 r, bytes32 s, uint256 deadline) sig)',
  'function getNonce(address sender) view returns (uint256)',
  'function moduleId() view returns (uint256)',
  'function moduleVersion() view returns (bytes32)',
  'function sell((address collection, uint256 tokenId) asset, ((bytes32 loanId, uint256 aggLoanPrice, uint256 aggLtv, uint256 aggLiquidationThreshold, uint88 totalAssets, uint256 nonce, uint256 deadline) loan, bytes32 assetId, address marketAdapter, address marketApproval, uint256 marketPrice, address underlyingAsset, address from, address to, bytes data, uint256 value, uint256 nonce, uint256 deadline) signSellNow, (uint8 v, bytes32 r, bytes32 s, uint256 deadline) sig)',
  'event ForceSold(bytes32 loanId, bytes32 assetId, address collection, uint256 tokenId, uint256 amount)',
  'event Genesis()',
  'event InstallerInstallModule(uint256 indexed moduleId, address indexed moduleImpl, bytes32 moduleVersion)',
  'event LoanCreated(address indexed user, uint256 indexed loanId, uint256 totalAssets, uint256 amount, uint256 borrowIndex)',
  'event ProxyCreated(address indexed proxy, uint256 moduleId)',
  'event Sold(bytes32 loanId, bytes32 assetId, address collection, uint256 tokenId, uint256 amount)',
  'error AccessDenied()',
  'error HealtyLoan()',
  'error InvalidCurrentLiquidationThreshold()',
  'error InvalidCurrentLtv()',
  'error InvalidLoanId()',
  'error InvalidRecoveredAddress()',
  'error LoanNotActive()',
  'error LoanNotUpdated()',
  'error NotAssetOwner()',
  'error NotEqualDeadline()',
  'error OrderActive()',
  'error SenderZeroAddress()',
  'error UnhealtyLoan()',
  'error WrongNonce()',
  'error ZeroAddress()'
] as const

export default sellNowInterface
